Matches= [{'Links': [{'Link': 'http://watchkobestreams.ml/soccer1.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://trimtreat.gq/Chelsea-FC-vs-AFC-Bournemouth.php',
             'Name': 'Chelsea FC vs. AFC Bournemouth English Stream'},
            {'Link': 'http://www.livexsports.com/soccer/watch/48',
             'Name': 'NBC Sports Gold English Stream **HD**'},
            {'Link': 'http://www.sportswatch.gq/p/adsbygoogle-window_82.html',
             'Name': 'English Stream'},
            {'Link': 'http://tuttosportweb.eu/ch34.html', 'Name': 'English'},
            {'Link': 'http://puitikstream.cf/stream.html',
             'Name': 'Arabic Streaming'},
            {'Link': 'http://c247.cf/bein5.html',
             'Name': 'Chelsea vs Bournemouth'},
            {'Link': 'http://www.golshoot.com/tv/ote-2.php',
             'Name': 'RUSSIAN STREAM'},
            {'Link': 'http://acesports.stream/live2.php', 'Name': 'EN Stream'},
            {'Link': 'http://lazioclub.gq/stream/kt5.php',
             'Name': 'Chelsea vs AFC Bournemouth English Stream'},
            {'Link': 'http://vettoristream.com/soccer3/',
             'Name': 'BEINSPORT 11 @English'},
            {'Link': 'http://ripple.is/football/1582-chelsea-vs-afc-bournemouth',
             'Name': 'Chelsea vs AFC Bournemouth'},
            {'Link': 'http://www.osmandembele.com/2018/01/chelsea-vs-bournemouth.html',
             'Name': 'Bein Sports 5'}],
  'MatchName': 'Chelsea vs AFC Bournemouth',
  'Teams': ['Chelsea', 'AFC Bournemouth'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://vettoristream.com/soccer/',
             'Name': 'BEINSPORT 11 @English'},
            {'Link': 'http://watchkobestreams.ml/soccer8.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://tuttosportweb.eu/ch29.html', 'Name': 'English'},
            {'Link': 'http://trimtreat.gq/Tottenham-Hotspur-vs-Manchester-United-bt1.php',
             'Name': 'Tottenham Hotspur vs. Manchester United English Stream '
                     '1'},
            {'Link': 'http://c247.cf/bein2.html',
             'Name': 'Tottenham vs Manchester United'},
            {'Link': 'http://www.sportswatch.gq/p/watch-16_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://www.livexsports.com/soccer/watch/49',
             'Name': 'NBC SN English Stream **HD**'},
            {'Link': 'http://puitikstream.cf/stream2.html',
             'Name': 'English Streaming'},
            {'Link': 'http://www.golshoot.com/tv/ukraina.php',
             'Name': 'RUSSIAN STREAM'},
            {'Link': 'http://lazioclub.gq/who/ktbtsport1.php',
             'Name': 'Tottenham Hotspur vs Manchester United BT 1 **HD** '
                     'English Stream'},
            {'Link': 'http://ripple.is/football/1584-tottenham-hotspur-vs-manchester-united',
             'Name': 'Tottenham Hotspur vs Manchester United'},
            {'Link': 'http://www.osmandembele.com/2018/01/blog-post_52.html',
             'Name': 'BT SPORT 1 '},
            {'Link': 'http://live-fs.com/live-news-premie-league/',
             'Name': 'ENGLISH 720p'}],
  'MatchName': 'Tottenham Hotspur vs Manchester United',
  'Teams': ['Tottenham Hotspur', 'Manchester United'],
  'Time': '20:00 GMT'},
 {'Links': [],
  'MatchName': 'Portugal vs Romania',
  'Teams': ['Portugal', 'Romania'],
  'Time': '17:00 GMT'},
 {'Links': [{'Link': 'http://www.golshoot.com/tv/futbol-ru-1.php',
             'Name': 'RUSSIAN STREAM'},
            {'Link': 'http://watchkobestreams.ml/soccer5.php',
             'Name': 'SPANISH'},
            {'Link': 'http://trimtreat.gq/AC-Milan-vs-Lazio-Roma.php',
             'Name': 'AC Milan vs. Lazio Roma Italian Stream'},
            {'Link': 'http://www.sportswatch.gq/p/watch-13_31.html',
             'Name': 'Italian Stream'},
            {'Link': 'http://tuttosportweb.eu/ch30.html', 'Name': 'English'},
            {'Link': 'http://lazioclub.gq/stream/kt1.php',
             'Name': 'Milan vs Lazio English Stream'}],
  'MatchName': 'Milan vs Lazio',
  'Teams': ['Milan', 'Lazio'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer7.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://www.sportswatch.gq/p/watch-15_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://trimtreat.gq/Stoke-City-vs-Watford FC.php',
             'Name': 'Stoke City vs. Watford FC English Stream'},
            {'Link': 'http://tuttosportweb.eu/ch4.html', 'Name': 'English'},
            {'Link': 'http://lazioclub.gq/stream/kt6.php',
             'Name': 'Stoke City vs Watford English Stream'}],
  'MatchName': 'Stoke City vs Watford',
  'Teams': ['Stoke City', 'Watford'],
  'Time': '20:00 GMT'},
 {'Links': [{'Link': 'http://www.golshoot.com/tv/bein-7.php',
             'Name': 'ARABIC STREAM'},
            {'Link': 'http://www.sportswatch.gq/p/watch-2_31.html',
             'Name': 'Morocco vs Libya ARA'},
            {'Link': 'http://trimtreat.gq/Morocco-vs-Libya.php',
             'Name': 'Morocco Vs Libya Arabic Stream'},
            {'Link': 'http://tuttosportweb.eu/ch36.html', 'Name': 'Arabic'}],
  'MatchName': 'Morocco vs Libya',
  'Teams': ['Morocco', 'Libya'],
  'Time': '16:30 GMT'},
 {'Links': [],
  'MatchName': 'Spain vs France',
  'Teams': ['Spain', 'France'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer3.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://www.sportswatch.gq/p/watch-11_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://tuttosportweb.eu/ch35.html', 'Name': 'English'},
            {'Link': 'http://trimtreat.gq/Newcastle-United-vs-Burnley-FC.php',
             'Name': 'Newcastle United vs. Burnley FC English Stream'},
            {'Link': 'http://c247.cf/bein12.html',
             'Name': 'Newcastle vs Burnley'},
            {'Link': 'http://lazioclub.gq/stream/kt4.php',
             'Name': 'Newcastle United vs Burnley English Stream'}],
  'MatchName': 'Newcastle United vs Burnley',
  'Teams': ['Newcastle United', 'Burnley'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer2.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://www.sportswatch.gq/p/watch-10_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://tuttosportweb.eu/ch1.html', 'Name': 'English'},
            {'Link': 'http://trimtreat.gq/Everton-FC-vs-Leicester-City.php',
             'Name': 'Everton FC vs. Leicester City English Stream'},
            {'Link': 'http://c247.cf/bein9.html',
             'Name': 'Everton vs Leicester City '},
            {'Link': 'http://www.golshoot.com/tv/ote-3.php',
             'Name': 'RUSSIAN STREAM'},
            {'Link': 'http://lazioclub.gq/stream/kt2.php',
             'Name': 'Everton vs Leicester City English Stream'},
            {'Link': 'http://www.osmandembele.com/2018/01/everton-vs-leicester-city.html',
             'Name': 'Bein Sports 9'}],
  'MatchName': 'Everton vs Leicester City',
  'Teams': ['Everton', 'Leicester City'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://tuttosportweb.eu/ch5.html', 'Name': 'Dutch'},
            {'Link': 'http://soccer.streamcartel.eu/s1.html?ch9 ',
             'Name': '  AZ Alkmaar vs Zwolle '},
            {'Link': 'http://trimtreat.gq/AZ-Alkmaar-vs-PEC-Zwolle.php',
             'Name': 'AZ Alkmaar vs Zwolle Dutch Stream'},
            {'Link': 'http://www.sportswatch.gq/p/watch-6_31.html',
             'Name': 'Dutch Stream'}],
  'MatchName': 'AZ Alkmaar vs Zwolle',
  'Teams': ['AZ Alkmaar', 'Zwolle'],
  'Time': '17:30 GMT'},
 {'Links': [{'Link': 'http://tuttosportweb.eu/ch7.html', 'Name': 'Spanish'},
            {'Link': 'http://www.sportswatch.gq/p/watch-19_31.html',
             'Name': 'Spanish Stream'},
            {'Link': 'http://www.golshoot.com/tv/antena-3.php',
             'Name': 'SPANISH STREAM'},
            {'Link': 'http://trimtreat.gq/Laganes-vs-Sevilla.php',
             'Name': 'Laganes vs Sevilla Spanish Stream'}],
  'MatchName': 'Leganes vs Sevilla',
  'Teams': ['Leganes', 'Sevilla'],
  'Time': '20:00 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer9.php',
             'Name': 'FRENCH'},
            {'Link': 'http://tuttosportweb.eu/ch23.html', 'Name': 'French'},
            {'Link': 'http://www.sportswatch.gq/p/watch-20_31.html',
             'Name': 'French Stream'},
            {'Link': 'http://trimtreat.gq/AS-Monaco-vs-Montpellier-HSC.php',
             'Name': 'AS Monaco vs. Montpellier HSC French Stream'}],
  'MatchName': 'Monaco vs Montpellier',
  'Teams': ['Monaco', 'Montpellier'],
  'Time': '20:00 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer10.php',
             'Name': 'SPANISH'}],
  'MatchName': 'Barcelona vs Valencia',
  'Teams': ['Barcelona', 'Valencia'],
  'Time': '20:00 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer6.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://www.sportswatch.gq/p/watch-14_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://vettoristream.com/soccer2/',
             'Name': 'BEINSPORT 11 @English'},
            {'Link': 'http://tuttosportweb.eu/ch2.html', 'Name': 'English'},
            {'Link': 'http://c247.cf/bein4.html',
             'Name': 'Manchester City vs WBA '},
            {'Link': 'http://trimtreat.gq/Manchester-City '
                     'vs-West-Bromwich-Albion.php',
             'Name': 'Manchester City vs. West Bromwich English Stream'},
            {'Link': 'http://www.livexsports.com/soccer/watch/47',
             'Name': 'NBC Sports Gold English Stream **HD**'},
            {'Link': 'http://puitikstream.cf/stream1.html',
             'Name': 'Arabic Streaming'},
            {'Link': 'http://www.golshoot.com/tv/ote-1.php',
             'Name': 'RUSSIAN STREAM'},
            {'Link': 'http://lazioclub.gq/stream/kt7.php',
             'Name': 'Manchester City vs West Bromwich Albion **HD** English '
                     'Stream'},
            {'Link': 'http://ripple.is/football/1583-manchester-city-vs-west-bromwich-albion',
             'Name': 'Manchester City vs West Bromwich Albion'},
            {'Link': 'http://www.osmandembele.com/2018/01/manchester-city-vs-west-brom.html',
             'Name': 'Bein Sports 4'}],
  'MatchName': 'Manchester City vs West Bromwich Albion',
  'Teams': ['Manchester City', 'West Bromwich Albion'],
  'Time': '20:00 GMT'},
 {'Links': [{'Link': 'http://tuttosportweb.eu/ch5.html', 'Name': 'Dutch'},
            {'Link': 'http://trimtreat.gq/Feyenoord-Rotterdam-vs-PSV-Eindhoven.php',
             'Name': 'Feyenoord vs PSV Dutch Stream'},
            {'Link': 'http://www.sportswatch.gq/p/watch-18_31.html',
             'Name': 'Dutch Stream'}],
  'MatchName': 'Feyenoord vs PSV',
  'Teams': ['Feyenoord', 'PSV'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://tuttosportweb.eu/ch33.html', 'Name': 'English'},
            {'Link': 'http://trimtreat.gq/Fraserburgh-vs-Rangers-FC.php',
             'Name': 'Fraserburgh vs. Rangers FC English Stream'},
            {'Link': 'http://www.sportswatch.gq/p/watch-17_31.html',
             'Name': 'English Stream'},
            {'Link': 'https://www.youtube.com/watch?v=MvqzT5K3g6Y',
             'Name': 'YouTube Stream'}],
  'MatchName': 'Fraserburgh vs Rangers',
  'Teams': ['Fraserburgh', 'Rangers'],
  'Time': '19:45 GMT'},
 {'Links': [{'Link': 'http://watchkobestreams.ml/soccer4.php',
             'Name': 'ENGLISH'},
            {'Link': 'http://www.sportswatch.gq/p/watch-12_31.html',
             'Name': 'English Stream'},
            {'Link': 'http://tuttosportweb.eu/ch3.html', 'Name': 'English'},
            {'Link': 'http://trimtreat.gq/Southampton-FC-vs-Brighton-and-Hove-Albion-FC.php',
             'Name': 'Southampton FC vs. Brighton and Hove Albion FC English '
                     'Stream'},
            {'Link': 'http://c247.cf/bein7.html',
             'Name': 'Southampton vs Brighton'},
            {'Link': 'http://lazioclub.gq/stream/kt3.php',
             'Name': 'Southampton vs Brighton & Hove Albion English Stream'}],
  'MatchName': 'Southampton vs Brighton & Hove Albion',
  'Teams': ['Southampton', 'Brighton & Hove Albion'],
  'Time': '19:45 GMT'}]
